### ISSUE TITLE
Sugestão - page_description

### ISSUE THREAD

**Issue by ghost** [fnando/page_title#1]
Seria interessante ter um método para adicionar descrição a página, podendo utilizar como meta tag ou na própria view.

Exemplo:
```ruby
 %meta{:name => "description", :content => page_description}
```
Ou na View:

```ruby
 .page_header
  %h1
   = page_title
   %small
    %i.icon-double-angle-right
    = page_description
```

Abraço.

**Comment by fnando** [comment]
Dá uma olhada em https://github.com/fnando/page_meta. ;)
